name: SubtleTemplates
author: Thomas Aylott (SubtleGradient)

category: Utilities
tags: [template, JSON, data binding]

docs: http://github.com/subtleGradient/mootools-subtle-templates/blob/master/Docs/SubtleTemplate.md
demo: http://subtlegradient.github.com/mootools-subtle-templates/Demos/demo.html
